<?php

return [
    'counties' => [
        'Nairobi' => [
            'Westlands', 'Karen', 'Kilimani', 'Lavington', 'Runda', 'Gigiri', 'Eastlands',
            'Upper Hill', 'CBD', 'South B', 'South C', 'Embakasi', 'Donholm', 'Ruaka',
            'Parklands', 'South C', 'Hurlingham', 'Loresho', 'Kitisuru', 'Spring Valley',
            'Muthaiga', 'Ridgeways', 'Nyari', 'Kileleshwa', 'Adams Arcade', 'Ngong Road',
            'Dagoretti', 'Kawangware', 'Kangemi', 'Mountain View', 'Umoja', 'Kayole',
            'Rongai', 'Ongata Rongai', 'Langata', 'Syokimau', 'Athi River',
        ],
        'Kiambu' => [
            'Thika', 'Kiambu Town', 'Ruiru', 'Kikuyu', 'Limuru', 'Gatundu', 'Juja',
            'Kabete', 'Lari', 'Githunguri', 'Other',
        ],
        'Mombasa' => [
            'Nyali', 'Likoni', 'Mvita', 'Kisauni', 'Changamwe', 'Jomvu', 'Bamburi',
            'Shanzu', 'Mtwapa', 'Other',
        ],
        'Kisumu' => [
            'Kisumu Central', 'Kondele', 'Milimani', 'Nyalenda', 'Kajulu', 'Other',
        ],
        'Nakuru' => [
            'Nakuru Town', 'Naivasha', 'Gilgil', 'Molo', 'Njoro', 'Other',
        ],
        'Machakos' => [
            'Machakos Town', 'Athi River', 'Kangundo', 'Tala', 'Other',
        ],
        'Kajiado' => [
            'Kajiado Town', 'Ongata Rongai', 'Kitengela', 'Ngong', 'Other',
        ],
        'Meru' => ['Meru Town', 'Maua', 'Nkubu', 'Other'],
        'Uasin Gishu' => ['Eldoret', 'Kapsabet', 'Other'],
        'Kakamega' => ['Kakamega Town', 'Mumias', 'Other'],
        'Kisii' => ['Kisii Town', 'Suneka', 'Other'],
        'Nyeri' => ['Nyeri Town', 'Karatina', 'Other'],
        'Embu' => ['Embu Town', 'Runyenjes', 'Other'],
        'Tharaka-Nithi' => ['Chuka', 'Chogoria', 'Other'],
        'Kirinyaga' => ['Kerugoya', 'Sagana', 'Other'],
        'Muranga' => ['Muranga Town', 'Kenol', 'Other'],
        'Nyandarua' => ['Ol Kalou', 'Nyahururu', 'Other'],
        'Laikipia' => ['Nanyuki', 'Rumuruti', 'Other'],
        'Narok' => ['Narok Town', 'Other'],
        'Kericho' => ['Kericho Town', 'Litein', 'Other'],
        'Bomet' => ['Bomet Town', 'Sotik', 'Other'],
        'Kwale' => ['Ukunda', 'Lunga Lunga', 'Other'],
        'Kilifi' => ['Malindi', 'Kilifi Town', 'Other'],
        'Tana River' => ['Hola', 'Garsen', 'Other'],
        'Lamu' => ['Lamu Town', 'Other'],
        'Taita-Taveta' => ['Voi', 'Wundanyi', 'Other'],
        'Garissa' => ['Garissa Town', 'Other'],
        'Wajir' => ['Wajir Town', 'Other'],
        'Mandera' => ['Mandera Town', 'Other'],
        'Marsabit' => ['Marsabit Town', 'Other'],
        'Isiolo' => ['Isiolo Town', 'Other'],
        'Kitui' => ['Kitui Town', 'Other'],
        'Makueni' => ['Wote', 'Mtito Andei', 'Other'],
        'Turkana' => ['Lodwar', 'Kakuma', 'Other'],
        'West Pokot' => ['Kapenguria', 'Other'],
        'Samburu' => ['Maralal', 'Other'],
        'Trans-Nzoia' => ['Kitale', 'Other'],
        'Elgeyo-Marakwet' => ['Iten', 'Other'],
        'Nandi' => ['Kapsabet', 'Other'],
        'Baringo' => ['Kabarnet', 'Other'],
        'Vihiga' => ['Mbale', 'Other'],
        'Bungoma' => ['Bungoma Town', 'Other'],
        'Busia' => ['Busia Town', 'Other'],
        'Siaya' => ['Siaya Town', 'Other'],
        'Homa Bay' => ['Homa Bay Town', 'Other'],
        'Migori' => ['Migori Town', 'Other'],
        'Nyamira' => ['Nyamira Town', 'Other'],
    ],
];
